services:

  finly_finance_db:
    image: postgres:latest
    container_name: finly_finance_db
    environment:
      POSTGRES_DB: finly_finance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - finly-network

    ports:
      - "5432:5432"

networks:
  finly-network:
    driver: bridge