spring:
  application:
    name: finly-finance

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/finly_finance_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate # flyway controla todo o schema e o jpa faz as validações
    #    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

